-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.**
-keep,includedescriptorclasses class com.dexter.data.**$$serializer { *; }
-keepclassmembers class com.dexter.data.** { *** Companion; }
-keepclasseswithmembers class com.dexter.data.** { kotlinx.serialization.KSerializer serializer(...); }
